import os
from enum import Enum

# === разрешение основной игры ===
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
CAMERA_ZOOM = 1.5


# === все что связано с игроком ===
PLAYER_SIZE = 64
PLAYER_SPEED = 200
PLAYER_MAX_HP = 120


# === ВРАГИ ===
# оранжевый глаз (первый враг!!!)
ORANGE_EYE_HP = 90
SHOTGUN_ENEMY_HP = 105
ORANGE_EYE_SPEED = 200
ORANGE_EYE_COOLDOWN = 1.0
SNIPER_EYE_HP = 80
SNIPER_EYE_SPEED = 130
SNIPER_EYE_COOLDOWN = 1.8

# === все что связано с тайлингом ===
TILE_SIZE = 32
MIN_CORRIDOR_WIDTH = 3
MIN_ROOM_SIZE = 10
MIN_AREA_SIZE = 12

class Tiles(Enum):
    FLOOR = 1
    WALL = 2


# === все что связано с пулями ===
PLAYER_BULLET_SIZE = 10
PLAYER_BULLET_VELOCITY = 400
PLAYER_FIRE_COOLDOWN = 0.15
PLAYER_BULLET_DAMAGE_RANGE = (22, 34)
ENEMY_BULLET_VELOCITY = 400
ENEMY_BULLET_DAMAGE_RANGE = (8, 12)
SNIPER_BULLET_VELOCITY = 600
SNIPER_BULLET_DAMAGE_RANGE = (10, 14)
HEAT_DROP_RANGE = (8, 12)
HEAT_PICKUP_SIZE = 18
